
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datacentre-db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      nodeSelector:
        db: main
      volumes:
        - name: mysqldb
          nfs:
            path: /nas/data/mysql
            server: 192.168.1.131
        - name: elasticsearchdb
          nfs:
            path: /nas/data/elasticsearch
            server: 192.168.1.131
      containers:
        - name: mysql
          image: mysql:8.0.21
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldb
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: xiefei
        - name: elasticsearch
          image: elasticsearch:7.8.0
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearchdb
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          env:
            - name: discovery.type
              value: single-node

---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: esdb
spec:
  selector:
    app: db
  ports:
    - port: 9200
      targetPort: 9200
  type: NodePort